### PR TITLE
updated to swift 3 syntax

### PR DESCRIPTION
**Pull request by ksinghal**
Hey I have updated the library to support Swift 3. I hope this helps

### CODE REVIEW

**Comment by zenangst** [comment]
Hey @ksinghal, thanks for the PR, could you point it to the `swift-3` branch instead of `master`? :)

**Comment by ksinghal** [comment]
happy to help, I just did

**Comment by zenangst** [comment]
@ksinghal could you change the travis configuration to use Xcode 8?

**Comment by ksinghal** [comment]
strange, it still seems to be compiling using swift 2.2/2.3 instead of 3.0. I switched the travis configuration to xcode 8

**Comment by zenangst** [comment]
Lets see what happens, fingers crossed 😁

**Comment by ksinghal** [comment]
it failed :( . see this issue: https://github.com/facebook/xctool/issues/704

**Comment by zenangst** [comment]
Maybe if you change it to use `xcodebuild` instead of `xctool`.

So change;
```
xctool clean build -project ImagePicker.xcodeproj -scheme ImagePicker-iOS -sdk iphonesimulator
```

To:

```
xcodebuild test -project ImagePicker.xcodeproj -scheme ImagePicker-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
```

**Comment by ksinghal** [comment]
nice! thanks for the pointers, all seems well

**Comment by ksinghal** [comment]
I'm going to now update the readme for minor swift 3 changes now that the CI has passed it's tests

**Comment by zenangst** [comment]
@ksinghal 

slack-imgs-2 com

**Comment by zenangst** [comment]
@ksinghal 
2jaaio9

**Pull request merged**
