### PR TITLE
Status bar initial state

### PR DESCRIPTION
**Pull request by RamonGilabert**

### CODE REVIEW

**Comment by RamonGilabert** [comment]
This fixes #69, it will take the current state of the status bar, and before dismissing it put it again.

**Comment by vadymmarkov** [comment]
@RamonGilabert Cool icon, man!

**Comment by RamonGilabert** [comment]
RIGHT?

**Comment by vadymmarkov** [comment]
Could we use this one? https://github.com/hyperoslo/ImagePicker/blob/master/Resources/ImagePickerIcon.png

**Comment by zenangst** [comment]
@RamonGilabert gluten free :cake: for you!

**Pull request merged**
