### PR TITLE
remove forced try statement

### PR DESCRIPTION
**Pull request by moriturus**
T/O

### CODE REVIEW

**Comment by richardoti** [comment]
Hi, @moriturus, is it an issue? Does it crash in some cases with `try!` ?

The delegate method `func audioSessionActivity(activity: Bool, didChangeWithError error: ErrorType?)` reveals internal implementation of ImagePicker, so `ImagePickerDelegate` is not the place to put these callback.

If it causes crash or misbehavior, it's better to put error-handling callbacks not related to images to a separate delegate.

**Comment by RamonGilabert** [comment]
I don't think we should have that delegate method telling there was an audio session error. If there ever was an error, Image Picker should handle it, the same thing as if the user doesn't grant the permission to the camera, is not a concern of the person that does the app, but rather, of the component `ImagePicker` to handle that.

@zenangst and @vadymmarkov.

**Comment by vadymmarkov** [comment]
Forced try is not good, but to handle that we could add `try` and `catch` it silently, or log an error. But don't see any sense to add one more method in `ImagePickerDelegate`.

**Comment by zenangst** [comment]
@moriturus hey, do you think you could move this into another delegate on `ImagePicker`?

I guess you could call it something like `ImagePickerErrorDelegate`.
What do you think?

**Comment by moriturus** [comment]
@richardoti In my product's case, there was a need to handle change of `AVAudioSession`'s activity so I implement the method `-audioSessionActivity:didChangeWithError:`. But now, I feel it is ugly as @RamonGilabert and @vadymmarkov said.
And I prefer the way @zenangst shown, may I re-open a pull-request with the codes its way?

**Comment by zenangst** [comment]
You could argue that the implementation should handle the error case correctly without the need to have a error handling delegate. Like showing an appropriate message when things fail instead of handing the task over to another fellow developer :)

You can always re-open or make new pull requests.

**Comment by RamonGilabert** [comment]
Going to close this PR for now, since there hasn't been much activity in 30 days but feel free to make another PR with the comments. :)

**Pull request closed without merging**
