### PR TITLE
limit users to selecting only one photo

### PR DESCRIPTION
**Pull request by leojkwan**
Add custom property to Configuration that limits photo selection to one. Simply animate deselection of visible cells in 'didSelectItem', and remove selected photos from photo stack array.

### CODE REVIEW

**Comment by leojkwan** [comment]
Might solve use case #200, or general profile picture selection etc.

**Comment by aashishdhawan** [comment]
@leojkwan This is already a property called `imageLimit` to limit number of selected images.
For example you can limit users to select only one image with this 

```Swift
    let imagePicker = ImagePickerController()
    imagePicker.imageLimit = 1
    imagePicker.delegate = self

    present(imagePicker, animated: true, completion: nil)
```

How your pull request is different from this?

**Comment by SamreenShigri** [comment]
Done Button isn't working..
imagePicker.delegate = self gives error

**Comment by aashishdhawan** [comment]
@SamreenShigri  Please check already opened issues, i think you might find your concerns already mentioned in issues list. If not, Please open separate issues for your concerns.

**Comment by aashishdhawan** [comment]
@leojkwan ping.

**Comment by leojkwan** [comment]
Hi @aashishdhawan. I thought the imageLimit property would do the trick. However, the main difference between 'imageLimit' and this PR is the *resetting* of selected images on selections beyond the limit. For example, if the imageLimit property is set to 1, a user cannot select another image until the first selected image is deselected. 

Using the example above, when 'allowMultiplePhotoSelection' is set to true, the selected image is *overridden* by newly selected image. The example use case is selecting an appropriate profile picture. 

Perhaps the naming of this configuration can be improved as it might be confusing with 'imageLimit', but I do think it's worthwhile to provide this flexibility!

**Comment by zenangst** [comment]
@leojkwan this looks really good, thanks for contributing :)

**Comment by nderkach** [comment]
Wouldn't it make sense to enable this parameter by default? For example it looks really awkward when you set `imageLimit` to 1 and try to select another picture. One would expect the selection to change automatically without having to deselect the previous selection.

**Comment by leojkwan** [comment]
@nderkach hmm that's a good idea, id say open a feature/enhancement request and see if everyone is on board!

**Pull request merged**
