### PR TITLE
Added the ability to save photos without loss of location and exif metadata, fixed several bugs

### PR DESCRIPTION
**Pull request by raketenok**
1. Added the ability to save photos without loss of location and exif metadata
(Now the photo album stores the data. (which store the exif metadata and the gps coordinates) not UIImage. 
If you set the quality of the photo (ImagePickerController.photoQuality = AVCaptureSession.Preset.photo), then after creating the snapshot, we will call the delegates
(func wrapperDidPress(images: [(imageData: Data,location: CLLocation?)])
  func doneButtonDidPress(images: [(imageData: Data,location: CLLocation?)])), which will return the data. If the picture quality is not set in advance, the old delegate method will be called
2. Fixed bug when clicking and dragging(outside the photo button)
3. Fixed bugs when clicking the Done/Cancel/PhotoStack button again

### CODE REVIEW

**Comment by ElectroBuddha** [comment]
I have merged this pull request into my fork. There is an issue when tapping on 'wrapper' button when no images are selected: 
 - the delegate methods 'wrapperDidPress' do not fire, 
 - the 'cancel' button becomes unresponsive too. 

After quick analysis, I have found out that your method `resolveAssets(_ assets:, imagesClosers: )` does not call 'imagesClosers' callback in case when 'assets' array is empty. Fixed it by adding this line before `for asset in assets {...}` loop:
```
guard !assets.isEmpty else { return imagesClosers(imagesData) }
```

Also, could you please pass 'imagePicker' reference in your new delegate methods `wrapperDidPress(images: [(imageData: Data,location: CLLocation?)])` and `doneButtonDidPress(images: [(imageData: Data,location: CLLocation?)])` so that they have similar signature as original delegate methods, because the host application might need that reference inside delegate methods.

**Comment by raketenok** [comment]
Fixed, you can review

**Comment by sedwo** [comment]
@raketenok Can you please update the `ImagePickerDemo` to demonstrate your changes, as it currently breaks things.

**Comment by raketenok** [comment]
I added a description, made the methods optional and updated the demo

**Pull request closed without merging**
