### PR TITLE
Changed how status bar appear/disappear

### PR DESCRIPTION
**Pull request by JARMourato**
Pull Request for issue #94  :)

### CODE REVIEW

**Comment by zenangst** [comment]
Hey @JARMourato, seems like you are using a different indentation setting than we do, would you mind using 2 spaces to fix up this PR? Btw, thanks for contributing :sunglasses:

**Comment by JARMourato** [comment]
Sure @zenangst , no problem. Will do now :)

**Comment by zenangst** [comment]
Hmm, that can't be right? I see more spacing now 🤔

**Comment by JARMourato** [comment]
How about now ?

**Comment by zenangst** [comment]
@JARMourato fantastic!

**Comment by zenangst** [comment]
unknown-9

**Pull request merged**
