### PR TITLE
Can Disable Camera Rotation

### PR DESCRIPTION
**Pull request by kernjackson**
Adds a configuration item for disabling camera rotation button.

### CODE REVIEW

**Comment by RamonGilabert** [comment]
I think @zenangst did something similar here, I'll let him take a step up on this. Also, sorry about the late replay, we should answer within a week, but this has gone places, a lot of work in the office and stuff to do. Sorry about that.

**Comment by zenangst** [comment]
For me, calling it camera rotation is a bit confusing but that is beside the point. To clarify, I worked a bit on the rotation, not the option to disable the front-facing camera.

@kernjackson could you fix the merge conflicts on this PR? :sunglasses:

**Comment by kernjackson** [comment]
Right, canRotate is kind of confusing. I was just trying to follow the existing naming convention. Maybe could have called it banSelfies or something like that. :smile:

**Comment by zenangst** [comment]
@kernjackson thanks mate! Sorry for the delay

**Pull request merged**
