### PR TITLE
Added photo quality parameter to configurations

### PR DESCRIPTION
**Pull request by Lumyk**

### CODE REVIEW

**Comment by Lumyk** [comment]
@3lvis

**Comment by 3lvis** [comment]
Hi Evgeny, so sorry for the lack of reply on this PR. Been quite busy with several other projects.

**Comment by Lumyk** [comment]
> Hi Evgeny, so sorry for the lack of reply on this PR. Been quite busy with several other projects.

It was big update, i can split it by smaller pr, if you interested

**Comment by 3lvis** [comment]
That would be great but more importantly people have been asking for more quality. What’s the reasoning for adding it as a setting rather than bumping up the current quality?

**Pull request closed without merging**
