### PR TITLE
Add option to default to the front camera instead of the back camera

### PR DESCRIPTION
**Pull request by rlmartin**

### CODE REVIEW

**Comment by zenangst** [comment]
Hey @rlmartin, looks like this PR is using `2.3` syntax. `master` is `swift-3` so we cannot merge I'm afraid.

**Comment by rlmartin** [comment]
Sorry @zenangst - not sure what happened. I am indeed using the swift-2.3 branch, but I thought I had cherry-picked the changes over correctly. The latest version looks a lot better.

**Comment by zenangst** [comment]
@rlmartin Mind pointing this to the correct branch, then we can merge it :)

**Comment by rlmartin** [comment]
@zenangst sorry if I wasn't being clear. This change is intended for both your master (Swift 3) and swift-2.3 branches. This current PR is for Swift 3/master. I do have a separate commit for the swift-2.3 branch - which I can also submit as a PR - but I wasn't sure what your process was around keeping that branch current with master.

That aside, this PR is Swift-3-compatible. Tell me if there are any specific things you would like me to change. We can deal with the Swift 2.3 commit separately.

**Comment by zenangst** [comment]
@rlmartin  Oh... such confusion haha 😎

**Comment by zenangst** [comment]
This looks good to me, what do you think @hyperoslo/ios ?

**Comment by RamonGilabert** [comment]
Great @rlmartin!

**Comment by rlmartin** [comment]
Thanks for merging - I'll submit the PR for the swift-2.3 branch now, if you'd like it.

**Pull request merged**
