### PR TITLE
Fix/remove cancel button

### PR DESCRIPTION
**Pull request by richardoti**
Now, the only button is `Done` and if Picker is empty, it returns empty array.

### CODE REVIEW

**Comment by zenangst** [comment]
@hyperoslo/myshop-ios we don't need the cancel button anymore?

**Comment by richardoti** [comment]
@zenangst I've talked to @RamonGilabert before implementing this and we agreed to remove cancel button completely.

**Comment by gilstad** [comment]
@richardoti @RamonGilabert Do you mean removing the "Done" button in the full screen image gallery?

**Comment by RamonGilabert** [comment]
@gilstad you are everywhere! :) Well, Richard told me to just display Done instead of Cancel, since, when you select 4 images and you deselect them, you are also done for instance, you don't want to cancel I guess. The reason behind it was like that right @richardoti?

**Comment by richardoti** [comment]
@gilstad, no. I mean this "Cancel" button:
screen shot 2015-08-26 at 17 09 20

So, the bottom view of the screen will always look like this - "Done" instead of context-dependent "Done"/"Cancel"
ios simulator screen shot 26 aug 2015 17 09 01

The reason for this change, as @RamonGilabert pointed, because now it is impossible remove all the photos if user selected any. One photo will always be selected - because "Cancel" button does not apply changes, it just dismisses the screen. The only way to remove all photos - close and reopen composer.

With this fix changes are being applied always, so if you remove all the photos, you can press "Done" and no photos will be attached to the post.

**Comment by gilstad** [comment]
@RamonGilabert I dont read everything on git in detail, but I try to get an overview of the things happening. If I see something that I think goes in the wrong direction I comment ;)

I don't see the reason for not allowing to remove all images. This should be possible. If the user don't want to add pictures anyway we should not force him to close the whole composer.

Se we should keep the two options the button in question
- Before any picture is captured and if all pictures are deselected -> Cancel
- When one or more picture is selected -> Done

**Comment by richardoti** [comment]
@gilstad I agree with the idea of allowing user to deselect all the images - it is exact reason, why I did this pull request. Now it is impossible to do.

`if all pictures are deselected -> Cancel ` - then user just dismisses the ImagePicker and does not do any changes, i.e. cannot remove the images as his action would be cancelled.

If we use only `Done` button - it is clear that all the changes will be saved. When user presses `Done`, all the selected images are being taken by the composer. If he presses `Cancel` - all changes are discarded -> composer has all the images that it had before.

I hope, it's clear, but if you want, I can show you the live demo of the case I am talking about.

**Pull request closed without merging**
