### PR TITLE
Master

### PR DESCRIPTION
**Pull request by allenlinli**
Converted source file to Swift3.0

### CODE REVIEW

**Comment by freesuraj** [comment]
can someone update on this?

**Comment by zenangst** [comment]
I'm a bit confused by this PR 😁

**Comment by RamonGilabert** [comment]
Feel free to comment with your addition and I will reopen the PR, as for now. I'm closing it :)

**Comment by allenlinli** [comment]
I feel like to add a space there...
Sorry something went wrong 😁

Swift 3 is annoying, isn't it?

**Comment by freesuraj** [comment]
I waited for you guys to fix this for swift 3.. ended up writing my own small wrapper.. would love to try this one when you've a swift 3 version.

Keep up the good work

**Pull request closed without merging**
