### PR TITLE
Updating code to swift 4.2

### PR DESCRIPTION
**Pull request by sameh0**

### CODE REVIEW

**Comment by bilawal-liaqat** [comment]
@sameh0 
How we can update Pod to support swift 4.2 ?

**Comment by sameh0** [comment]
> @sameh0
> How we can update Pod to support swift 4.2 ?

What do you mean ?

**Comment by bilawal-liaqat** [comment]
@sameh0 
I'm installing pod using `pod 'ImagePicker' ` but its not installing swift 4.2 compatible pod. 
How can I install swift 4.2 compatible ImagePicker po ?

**Comment by sameh0** [comment]
pod 'Lightbox' , :git => 'https://github.com/sameh0/Lightbox' , :branch => 'master'


> @sameh0
> I'm installing pod using `pod 'ImagePicker' ` but its not installing swift 4.2 compatible pod.
> How can I install swift 4.2 compatible ImagePicker po ?

pod 'ImagePicker' , :git => 'https://github.com/sameh0/ImagePicker' , :branch => 'master'

**Comment by sameh0** [comment]
> @sameh0
> I'm installing pod using `pod 'ImagePicker' ` but its not installing swift 4.2 compatible pod.
> How can I install swift 4.2 compatible ImagePicker po ?

pod 'ImagePicker' , :git => 'https://github.com/sameh0/ImagePicker' , :branch => 'master'

**Pull request closed without merging**
