### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by autumnssun**
Swift 4 enabled
Tested with xcode 9 beta 6

### CODE REVIEW

**Comment by onmyway133** [comment]
@autumnssun Hi, this is great. 🚀

**Comment by zenangst** [comment]
Hey @autumnssun, I just created a `swift4` branch. Would you mind pointing your PR against that branch instead of `master` ? 😎

**Comment by NinoScript** [comment]
Is there something stopping this from getting merged? Can I help in any way?

**Comment by JoniVR** [comment]
> Is there something stopping this from getting merged? Can I help in any way?

@NinoScript Wondering the same thing

Let me know if there's anything I can do to help.

**Comment by onmyway133** [comment]
@autumnssun Hi, many thanks for the PR 🚀

**Pull request merged**
